stages:
    - dist
    - build
    - repo

dist beta:
    tags:
        - dist
    stage: dist
    script:
        - make dist-gzip
        - VERSION=$(git describe --tags --always)
        - rpmdev-bumpspec --new=${VERSION} lexonomy-beta.spec
        - mock --verbose -r /etc/mock/ske/fedora-32-x86_64.cfg --buildsrpm --spec lexonomy-beta.spec --sources . --resultdir .
    artifacts:
        paths:
            - "*.src.rpm"
            - "*.tar.gz"
    rules:
        - if: '$CI_COMMIT_TAG && $CI_COMMIT_TAG =~ /^beta-.*/'

build f32:
    tags:
        - mock
    stage: build
    script:
        - mock --verbose -r /etc/mock/ske/fedora-32-x86_64.cfg --rebuild lexonomy-*.src.rpm --resultdir .
    except:
        - branches
    artifacts:
        paths:
        - "*fc32*.rpm"

build f36:
    tags:
        - mock
    stage: build
    script:
        - mock --verbose -r /etc/mock/ske/fedora-36-x86_64.cfg --rebuild lexonomy-*.src.rpm --resultdir .
    except:
        - branches
    artifacts:
        paths:
        - "*fc36*.rpm"

update repo:
    tags:
        - repo
    stage: repo
    script:
        - mv *.fc32.src.rpm /rpm_packages/f32_src/
        - createrepo_c --update /rpm_packages/f32_src
        - mv *.fc32.*.rpm /rpm_packages/f32/
        - createrepo_c --update /rpm_packages/f32
        - mv *.fc36.src.rpm /rpm_packages/f36_src/
        - createrepo_c --update /rpm_packages/f36_src
        - mv *.fc36.*.rpm /rpm_packages/f36/
        - createrepo_c --update /rpm_packages/f36
    except:
        - branches
    dependencies:
        - build f32
        - build f36

