matrix:
  include:
    - language: node_js
      node_js:
        - "12"
      before_script:
        - cd website
        - npm install --ignore-scripts
      script:
        - npm run lint

    - language: python
      python: 
        - 3.5
        - 3.6
      before_script:
        - cd website
        - pip install -r requirements-dev.txt
      script:
        - pylint --exit-zero --disable=invalid-name lexonomy.py
