version: '3.4'

x-custom:
  service: &service
    image: node:11
    volumes:
      - .:/opt/service
      - nodemodules:/opt/service/website/node_modules
    working_dir: /opt/service/website
  service_env: &service_env
    LEXONOMY_SITECONFIG: siteconfig.json.template

services:
  build:
    <<: *service
    command: npm run build
    environment:
      <<: *service_env
  create-bundles:
    <<: *service
    command: npm run create-bundles
    environment:
      <<: *service_env
  dev:
    <<: *service
    command: npm run dev
    environment:
      <<: *service_env
      NODE_ENV: development
    ports:
      - "8080:8080"

volumes:
  nodemodules:
    external: true
