import './libs/riot/riot.js'
import './libs/riot/route.js'
import './libs/riot/observable.js'
import './libs/materialize/materialize.min.js'
import './libs/materialize/materialize-colorpicker.min.js'
import './libs/fuzzysort/fuzzysort.js'
